name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /home/wagumi/work/git-test
        remote_host: 52.140.201.81
        remote_user: wagumi
        remote_key: ${{ secrets.DEPLOY_KEY }}
